version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./db:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kritikverma2002/sharingapp
    ports:
      - 8000:8000
    environment:
      - MONGO_CONNECTION_URL=mongodb://mongoadmin:<PASSWORD>@mongodb
      - DATABASE_CONNECTION_PASSWORD=secret 
      - APP_BASE_URL=http://127.0.0.1:8000
      - PORT=8000